version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  backend:
    image: bsan89/whats-for-dinner-backend:latest
    build:
      context: ./backend
    ports:
      - "8083:8083"
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/app/data 
    depends_on:
      - mongo
    restart: always

  frontend:
    image: bsan89/whats-for-dinner-frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    restart: always

volumes:
  mongo-data: