version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  backend:
    image: bsan89/whats-for-dinner-backend:latest
    build:
      context: ./backend
    ports:
      - "8083:8083"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PATH_TO_DATA_GZ=${PATH_TO_DATA_GZ}
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/app/data 
    depends_on:
      - mongo
    restart: always
    
volumes:
  mongo-data: