export const fallbackCountries = {
  'en:costa-rica': 'CR',
  'en:united-states': 'US',
  'en:sweden': 'SE',
  'en:nicaragua': 'NI',
  'en:haiti': 'HT',
  'en:sint-maarten': 'SX',
  'en:saint-martin': 'MF',
  'en:dominican-republic': 'DO',
  'en:dominica': 'DM',
  'en:saint-kitts-and-nevis': 'KN',
  'en:saint-lucia': 'LC',
  'en:antigua-and-barbuda': 'AG',
  'en:barbados': 'BB',
  'en:grenada': 'GD',
  'en:saint-vincent-and-the-grenadines': 'VC',
  'en:trinidad-and-tobago': 'TT',
  'en:anguilla': 'AI',
  'en:aruba': 'AW',
  'en:curacao': 'CW',
  'en:caribbean-netherlands': 'BQ',
  'en:netherlands': 'NL',
  'en:belize': 'BZ',
  'en:guatemala': 'GT',
  'en:el-salvador': 'SV',
  'en:honduras': 'HN',
  'en:panama': 'PA',
  'en:colombia': 'CO',
  'en:venezuela': 'VE',
  'en:ecuador': 'EC',
  'en:peru': 'PE',
  'en:bolivia': 'BO',
  'en:paraguay': 'PY',
  'en:chile': 'CL',
  'en:argentina': 'AR',
  'en:uruguay': 'UY',
  'en:suriname': 'SR',
  'en:guyana': 'GY',
  'en:french-guiana': 'GF',
  'en:brasil': 'BR',
  'en:uk': 'GB',
  'en:united-kingdom': 'GB',
  'en:england': 'GB',
  'en:scotland': 'GB',
  'en:wales': 'GB',
  'en:ireland': 'IE',
  'en:republic-of-ireland': 'IE',
  'en:albania': 'AL',
  'en:andorra': 'AD',
  'en:armenia': 'AM',
  'en:azerbaijan': 'AZ',
  'en:belarus': 'BY',
  'en:bosnia-and-herzegovina': 'BA',
  'en:bulgaria': 'BG',
  'en:estados unidos': 'US',
  'en:états-unis': 'US',
  'en:usa': 'US',
  'en:u.s.a': 'US',
  'en:etats-unis': 'US',
  'en:e.u.a': 'US',
  'en:eua': 'US',
  'en:america': 'US',
  'en:mexico': 'MX',
  'en:méxico': 'MX',
  'en:mèxico': 'MX',
  'en:mexi': 'MX',
  'en:united kingdom': 'GB',
  'en:royaume-uni': 'GB',
  'en:great britain': 'GB',
  'en:deutschland': 'DE',
  'en:germany': 'DE',
  'en:allemagne': 'DE',
  'en:espagne': 'ES',
  'en:españa': 'ES',
  'en:spain': 'ES',
  'en:france': 'FR',
  'en:francia': 'FR',
  'en:italy': 'IT',
  'en:italia': 'IT',
  'en:italie': 'IT',
  'en:japan': 'JP',
  'en:japon': 'JP',
  'en:china': 'CN',
  'en:chine': 'CN',
  'en:canada': 'CA',
  'en:canadá': 'CA',
  'en:cánada': 'CA',
  'en:ue': 'EU',
  'en:eu': 'EU',
  'en:european union': 'EU',
  'en:union européenne': 'EU',
  'en:europäische union': 'EU',
  'en:non european union': 'EU',
  'en:union européenne et non union européenne': 'EU'
}

export const aliasMap = {
  'états-unis': 'united states',
  'estados-unidos': 'united states',
  'u.s.a.': 'united states',
  'regno unito': 'united kingdom',
  'reino unido': 'united kingdom',
  'europäische union': 'european union',
  'union européenne': 'european union',
  'unione europea': 'european union',
  'unione europea e non unione europea': 'european union',
  'unione europea e non-europea': 'european union',
  'unione europea e non-european union': 'european union',
  'unione europea e non-eu': 'european union',
  'unione europea e non-european': 'european union'

}

/**
 * Normalizes the country name to a standard format.
 *
 * @param {string} origin - The country name to normalize.
 * @returns {string} - The normalized country name.
 */
export function normalizeCountry (origin) {
  if (!origin) return ''
  const cleaned = origin.trim().toLowerCase()
  return aliasMap[cleaned] || cleaned
}
