export const originSynonyms: { [key: string]: string } = {
  usa: 'United States',
  USA: 'United States',
  'u.s.a': 'United States',
  'U.S.A': 'United States',
  'estados unidos': 'United States',
  'Estados Unidos': 'United States',
  'es:estados-unidos': 'United States',
  'états-unis': 'United States',
  'États-Unis': 'United States',
  California: 'United States',
  Californië: 'United States',
  'Royaume-Uni': 'United Kingdom',
  "stati uniti d'america": 'United States',
  España: 'Spain',
  Espagne: 'Spain',
  Ardèche: 'France',
  Belgique: 'Belgium',
  Canadá: 'Canada',
  Angleterre: 'United Kingdom',
  Scotland: 'United Kingdom',
  'Haute Provence': 'France',
  Ireland: 'United Kingdom',
  Deutschland: 'Germany',
  Pologne: 'Poland',
  Itálie: 'Italy',
  Italie: 'Italy',
  Équateur: 'Ecuador',
  'Arabie saoudite': 'Saudi Arabia',
  méxico: 'Mexico',
  México: 'Mexico',
  thailande: 'Thailand',
  Kenia: 'Kenya',
  Ouganda: 'Uganda',
  "Provence-Alpes-Côte d'Azur": 'France',
  Provence: 'France',
  Hawaii: 'United States',
  espagne: 'Spain',
  Ethiopië: 'Ethiopia',
  'royaume-uni': 'United Kingdom',
  uk: 'United Kingdom',
  italie: 'Italy',
  deutschland: 'Germany',
  japon: 'Japan',
  francia: 'France',
  canadá: 'Canada',
  eua: 'United States',
  brésil: 'Brazil',
  suisse: 'Switzerland',
  nederland: 'Netherlands',
  gréce: 'Greece',
  égypte: 'Egypt',
  'europäische union': 'European Union',
  'non union européenne': 'Non-EU',
  'non eu': 'Non-EU',
  'Union européenne': 'European Union',
  'European Union': 'European Union',
}
